### ISSUE TITLE
Remove <title>icon-name</title>?

### ISSUE THREAD

**Issue by jessejanderson** [planningcenter/icons#38]
Is there a reason we shouldn't remove the `<title>icon-name</title>` attribute from our icon svgs?

I hate that it becomes a tooltip at times, which is even more problematic when you have an actual `title` on an icon button, but when they over the specific icon stroke it gives them the icon title instead of the supplied one.

**Comment by chantastic** [comment]
always open to suggestion.

when we moved to this model, it was the only reliable way to provide the
accessibility affordances, consistently, with sprites, in a way that
doesn't demand additional app-side discipline.

if it's the pointer events that are the problem, can't you disable those
with a CSS selector?

`selector { pointer-events: none }`

**Comment by jessejanderson** [comment]
That's fair. I can do the pointer events workout. 👍

**Comment by chantastic** [comment]
let me know how that approach pans out.
maybe it's something we need to expose as an importable CSS file along with
the icons
