### ISSUE TITLE
Names scrambled on a few general set icons

### ISSUE THREAD

**Issue by dannydb** [planningcenter/icons#41]
![image](https://user-images.githubusercontent.com/419297/75994909-e2c86a00-5eb8-11ea-891c-94e52887b64c.png)

It appears these three are mixed up:

- `outlined-pdf-file` shows the text file icon
- `outlined-text-file` shows the video file icon
- `outlined-video-file` shows the pdf icon

**Comment by chantastic** [comment]
thanks so much for the issue @dannydb 🙏

released as `7.0.0-beta.5` on npm
