### ISSUE TITLE
Check-Ins path data bad because of delete icon

### ISSUE THREAD

**Issue by souporserious** [planningcenter/icons#48]
Because `delete` is a reserved word in JS [this line](https://github.com/planningcenter/icons/blob/master/paths/check-ins.js#L23) throws errors when trying to import any icon from the Check-Ins set. Maybe renaming to something like `remove` could fix this?

**Comment by jessejanderson** [comment]
This seems like a reasonable change to me. @jonsuh ?

**Comment by chantastic** [comment]
fixed in v9.0.0 by #53
